name: 📈 GitHub Metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}
          filename: metrics.svg
          output_action: file
          output_dir: ./ # ⬅️ Зберігає в корінь репозиторію
          base: activity, community, repositories, metadata
          config_timezone: Europe/Kyiv

      - name: List files (debug)
        run: ls -alh

      - name: Commit & Push metrics.svg
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add metrics.svg
          git commit -m "📊 Update GitHub metrics" || echo "No changes"
          git push
